### PR TITLE
SO_PASSCRED and SO_PEERCRED options

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by sathieu** [comment]
Note that those only work on stream (TCP) sockets (unfortuantely not on datagram=UDP sockets)

**Comment by sathieu** [comment]
ping!

**Comment by diegonehab** [comment]
Sorry. Was away. Right now, I don't have access to a Windows machine. However, if you apply these changes to options.c, will it still compile on Windows?

**Comment by sathieu** [comment]
2016-10-21 21:59 GMT+02:00 Diego Nehab <notifications@github.com>:

> Sorry. Was away. Right now, I don't have access to a Windows machine.
> However, if you apply these changes to options.c, will it still compile on
> Windows?
>
I don't know. I don't have access to a Windows machine too.

**Comment by BrisingrAerowing** [comment]
It will not.

**Comment by ewestbrook** [comment]
A bit of research suggests that on Windows these flags are only available in WSL (Windows Subsystem for Linux), which would explain the failure to compile in standard Windows environments.

We could potentially provide support driven by conditional compilation (e.g. `#ifdef SO_PASSCRED`). Behavior should, of course, degrade gracefully wherever they are not supported.  If this is desired, a PR to that effect would be welcome. 

We're reviewing open items in preparation for a release.  If action is needed here, please add a comment.  Otherwise, this issue will be closed on or after 24-Feb-2019.

Thanks!

**Comment by sathieu** [comment]
Closing, as I don't use this anymore.

**Pull request closed without merging**
