### PR TITLE
Allow CC and LD to be overrriden

### PR DESCRIPTION
**Pull request by diegonehab**

### CODE REVIEW

**Comment by ewestbrook** [comment]
At first I wondered whether we should do this similarly to MYCFLAGS et al, but then realized that while MYCFLAGS and such might need to be added to, CC and LD would only be replaced, if anything.  I like it.

**Comment by diegonehab** [comment]
Turns out this is not necessary if the user calls make CC=bla, but I dind't know about that until just now. And since the initial value of CC is cc, I think this won't work as expected. :/ Maybe we should revert the change. Shall I do it?

**Comment by ewestbrook** [comment]
Oh!  That's right, and I should have realized that too.  Yes, please.

**Comment by diegonehab** [comment]
Done. :/

**Comment by diegonehab** [comment]
Sorry about the noise.

**Pull request merged**
