### PR TITLE
add cmake

### PR DESCRIPTION
**Pull request by sonoro1234**
this is a CMakeList file for cmake that works with mingw (but maybe also with others or can be an starting point for that)
Needs LUA_INCLUDE_DIR and LUA_LIBRARY defined and also accepts LDIR and CDIR for install

### CODE REVIEW

**Comment by ewestbrook** [comment]
Thanks!  There's some makefile and build work going on for the upcoming release anyway.  Be nice to get mingw solid to go out with that.  Are you able to help with testing on mingw in general?  Does the current regular makefile work for you in that environment?

**Comment by sonoro1234** [comment]
I am not working with msys so I cant use regular makefiles (that why I made this PR)
I am working with a quite old luasocket so I dont know if this CMakeLists is still valid for master

**Comment by ewestbrook** [comment]
May I ask you to try with current master?

**Comment by ewestbrook** [comment]
Sorry, I misread.  You said no msys.

We are in need of Windows build testing with MinGW, cygwin, MSVC, and LuaRocks.  I'm trying to get my hands on a system to use but haven't yet.  Anyone who can help will receive hearty thanks.

**Comment by sonoro1234** [comment]
PR #273 is for actual master so this should be closed.

**Pull request closed without merging**
