### PR TITLE
Tag functions explicitly for shared library visibility

### PR DESCRIPTION
**Pull request by ewestbrook**
Functions tagged, makefile updated, LuaRocks rockspecs updated.

### CODE REVIEW

**Comment by ewestbrook** [comment]
Addresses #139

**Comment by diegonehab** [comment]
I just merged the pull request, but didn't see the pragmas. It's not that we need them. We didn't even need to mark all internal symbols. I still think this is not a good solution. It is best to have the default  be hidden, and only mark explicitly the three symbols we want to export. The best way to do this is to use the compiler option. The second best is to use the pragmas, because one day somebody will add an internal function to LuaSocket and forget to add the LUASOCKET_PRIVATE decoration. If this happens and the default still is hidden, no problem. The user simply forgot to document the fact that he expects a given function to be private. But if the default is visible, then all hell breaks loose.

I think LuaRocks is wrong (twice). Once for not using this option by default for every library. And again for not using it for LuaSocket since we do that explicitly in the makefile. This problem *will* bite somebody else in the future. It may even bite us. :(

**Comment by ewestbrook** [comment]
I agree completely.  I'm actually still working on the pragma approach.  (For some reason I'm getting a relocation error in the link phase.)  And I'm also not done trying to coerce LuaRocks into using `-fvisibility` without going all the way to `build.type='makefile'`.  But if we eventually have to go there, so be it; that'll still be better than this, for the reasons you just articulated.

**Comment by diegonehab** [comment]
I never used the pragma myself. Maybe it changes something besides the visibility? when you compare the object file generated with -fvisibility=hidden and with no -fvisibility but with the pragma, do the symbols end up in a different section?

**Comment by ewestbrook** [comment]
I'll look into that.  On a related topic, how do you feel about using `strip` during the `install` phase of the makefile?  It seems that distros commonly do that when they package builds.  Seems appropriate for non-debug builds.

**Comment by diegonehab** [comment]
The binary is indeed smaller. 6x smaller sounds a lot, but the library is 360k before stripping... :) I don't think it makes much difference. 

In Mac OS X, I saw no difference. But removing the MACOSX_DEPLOYMENT_TARGET did reduce size.

**Pull request merged**
