### PR TITLE
Rewrite try/protect in Lua, support table errors

### PR DESCRIPTION
**Pull request by mpeterv**

### CODE REVIEW

**Comment by diegonehab** [comment]
Merged  #162 that implements it in C.

**Comment by diegonehab** [comment]
Do

**Comment by mpeterv** [comment]
Probably not, there are a few implementations available on Lua wiki and elsewhere already.

**Comment by ignacio** [comment]
Would it be worth it to leave those links here for posterity?

**Comment by diegonehab** [comment]
I think so. Particularly because of the new idea of checking the private metatable to make sure the error was thrown by try(). Do these other Lua implementations use the same idea?

**Comment by moteus** [comment]
In my library i add special [unique key](https://github.com/moteus/lua-try/blob/master/src/try.c#L57) to error wrap table.

**Pull request closed without merging**
